# Generated by Django 6.0.3 on 2026-03-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='asunto',
            field=models.CharField(default='Consulta General', max_length=200),
        ),
    ]
